language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - flake8 .
  - black --diff .
  - coverage run --source='.' manage.py test mysite

after_script:
  - coveralls
